### ISSUE TITLE
UnboundLocalError: local variable 'a' referenced before assignment

### ISSUE THREAD

**Issue by rohit11544** [nidhihegde001/CRISMIS#1]
When I cloned this repo and try to use this tool It was showing me this error  **UnboundLocalError: local variable 'a' referenced before assignment**.

This is the screenshot of the error that I got 
![Screenshot (97)](https://user-images.githubusercontent.com/61901749/106356331-dcd74500-6324-11eb-8c62-1204a17bba53.png)

can anyone let me know how to fix this error??

**Comment by nidhihegde001** [comment]
If you look at the code carefully, the image is directly fetched from the URL **"https://pdsimage2.wr.usgs.gov/archive/mess-e_v_h-mdis-2-edr-rawdata-v1.0/MSGRMDS_1001/DATA/" + directory+ name** depending on the flag values used in the command, so as to eliminate the need for the images to be downloaded locally. Here, it is showing an error since the directory name you provided is local to your PC and does not conform to the directory structure of the official archive.

**Comment by rohit11544** [comment]
Thank you for your response now it worked . Hi, my name is Rohit , I am preparing to take part in GSoC 2021 in CERN so while viewing the previous projects I found your project. Actually I have some doubts in this project so can you explain me and give some guide lines how to prepare for GSoC @ CERN. I promise it wont take more time . Please contact me through rohit.b19@iiits.in email or my what's app number 7337007435 else you can give your email or accept my LinkedIn connection invitation so that we can have a chat. Expecting a quick and positive response. 

thank you.

**Comment by nidhihegde001** [comment]
Okay. send a request on linkedIn.

**Comment by rohit11544** [comment]
Thank you so much for a quick reply . I have sent you connection request can you check and accept it.

**Comment by rohit11544** [comment]
Hi Nidhi, can you just explain the out line of what you have done for this project  like what is the code for in each notebook do, and what algorithm did you use thats enough. Please kindly reply. This small thing will help me a lot for my gsoc preparation. ( you can reply here or to my email( rohit.b19@iiits.in) , else you can call or whats app to my phone 7337007435 )

**Comment by nidhihegde001** [comment]
Sure. I couldn't find your request on linkedin. See if you can send a message there, or else you can mail me at nidhihegde001@gmail.com. Would be happy to help.
